apiVersion: v1
kind: Service
metadata:
  name: pdf-generator-svc
  namespace: pdf-gen
spec:
  selector:
    app: pdf-generator
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
